---
title: "Publications"
editor: visual
---

[*Google Scholar Profile.*](https://scholar.google.com/citations?view_op=list_works&hl=zh-TW&hl=zh-TW&user=B7WnalUAAAAJ)

### Academic Publications

\* Denotes the corresponding author.

**\[12\]** **Improving Byzantine-resilience in Federated Learning via Diverse Aggregation and Adaptive Variance Reduction.** **Xiuhua Wang,** Shikang Li, Fengrui Fan, Shuai Wang, Yiwei Li, Yu Zheng. International Conference on Information and Communications Security (ICICS). 2025.

**\[11\] Efficient and Verifiable Multi-server Framework for Secure Information Classification and Storage.** Ziqing Guo, Yaohui Wang, Xuanyu Jin, **Xiuhua Wang\*,** Yuanyuan He, Yueyue Dai. International Conference on Information Security and Cryptology (Inscrypt). 2024. pp 191-210. \[[pub](https://link.springer.com/chapter/10.1007/978-981-96-4734-7_10)\]

**\[10\] Attribute-Based Access Control Encryption.** **Xiuhua Wang,** Mengyang Yu, Yaohui Wang, Yinjia Pi, Peng Xu, Shuai Wang, Hai Jin, Min Han. IEEE Transactions on Dependable and Secure Computing (IEEE TDSC). 2024. \[[pub](https://ieeexplore.ieee.org/abstract/document/10720426)\]

**\[9\] Encrypted video search with single/multiple writers.** Yu Zheng, Wenchao Zhang, Wei Song, **Xiuhua Wang\*,** Chong Fu. ACM Transactions on Multimedia Computing, Communications and Applications (ACM TOMM). 2024. pp 1-23. \[[pub](https://dl.acm.org/doi/abs/10.1145/3643887)\]

**\[8\] Differentially private and heterogeneity-robust federated learning with theoretical guarantee. Xiuhua Wang,** Shuai Wang, Yiwei Li, Fengrui Fan, Shikang Li, Xiaodong Lin. IEEE Transactions on Artificial Intelligence (IEEE TAI). 2024. \[[pub](https://ieeexplore.ieee.org/abstract/document/10643038)\]

**\[7\] Boosting semi-supervised federated learning with model personalization and client-variance-reduction.** Shuai Wang, Yanqing Xu, Yanli Yuan, **Xiuhua Wang,** Tony Q. S. Quek. IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP). 2023. pp 1-5. **Top 3% paper recognition.** \[[pub](https://ieeexplore.ieee.org/abstract/document/10096678)\]

**\[6\] Cryptography-inspired federated learning for generative adversarial networks and meta learning.** Yu Zheng, Wei Song, Minxin Du, Sherman S. M. Chow, Qian Lou, Yongjun Zhao, **Xiuhua Wang.** International Conference on Advanced Data Mining and Applications (ADMA). 2023. pp 393-407. \[[pub](https://link.springer.com/chapter/10.1007/978-3-031-46664-9_27)\]

**\[5\] Cross-domain access control encryption: arbitrary-policy, constant-size, efficient. Xiuhua Wang,** Sherman S. M. Chow. IEEE Symposium on Security and Privacy (Oakland S&P). 2021. pp 388-401. \[[pub](https://ieeexplore.ieee.org/abstract/document/9519503)\]

**\[4\] Access control encryption from group encryption. Xiuhua Wang,** Harry W. H. Wong, Sherman S. M. Chow. International Conference on Applied Cryptography and Network Security (ACNS). 2021. pp 417-441. \[[pub](https://link.springer.com/chapter/10.1007/978-3-030-78372-3_16)\]

**\[3\] Privacy-preserving multi-pattern matching.** Tao Zhang, **Xiuhua Wang,** Sherman S. M. Chow. International Conference on Security and Privacy in Communication Systems (SecureComm). 2016. pp 199-218. \[[pub](https://link.springer.com/chapter/10.1007/978-3-319-59608-2_11)\]

**\[2\] Combiners for chosen-ciphertext security.** Cong Zhang, David Cash, **Xiuhua Wang,** Xiaoqi Yu, Sherman S. M. Chow. International Computing and Combinatorics Conference (COCOON). 2016. pp 257-268. \[[pub](https://link.springer.com/chapter/10.1007/978-3-319-42634-1_21)\]

**\[1\] Privacy preserving credit systems.** Sherman S. M. Chow, Russell W. F. Lai, **Xiuhua Wang,** Yongjun Zhao. International Conference on Network and System Security (NSS). 2016. pp 184-199. \[[pub](https://link.springer.com/chapter/10.1007/978-3-319-46298-1_13)\]

### My Ph.D. Thesis

[Secure and More Practical Access Control Encryption.](https://www.proquest.com/openview/4d3f1b2cbea06113fd1ec04011efab34/1?pq-origsite=gscholar&cbl=2026366&diss=y)

[\
](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=OJFxBWMAAAAJ&citation_for_view=OJFxBWMAAAAJ:d1gkVwhDpl0C)